import streamlit as st

# Generates index.html – the complete Phase 3 "Beyond Clash Royale" HTML5 Canvas port
# Run once: python _gen_html.py
# Then double-click index.html to play.

PARTS = []
def w(*lines): PARTS.extend(lines)

# ── HTML head ────────────────────────────────────────────────────────────────
w(
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <meta name="description" content="Royal Clash Ultimate — Phase 3 Beyond Clash Royale! Features Hero Commanders, Roguelike Perks, 12 Cards, Pro Deck Cycling, Night Weather, and MVP Analytics!">',
'  <title>Royal Clash — Phase 3 Beyond Clash Royale</title>',
'  <link rel="preconnect" href="https://fonts.googleapis.com">',
'  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
'  <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@700&family=Outfit:wght@400;600;700&family=Roboto+Mono:wght@500;700&display=swap" rel="stylesheet">',
'  <style>',
'    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
'    body {',
'      background: radial-gradient(circle at 50% 15%, #1e1b4b 0%, #09090b 100%);',
'      display: flex; flex-direction: column;',
'      justify-content: center; align-items: center;',
'      min-height: 100vh; font-family: "Outfit", sans-serif; user-select: none;',
'      color: #f8fafc; overflow-x: hidden; padding: 10px;',
'    }',
'    .game-container {',
'      position: relative;',
'      display: flex; flex-direction: column; align-items: center;',
'    }',
'    #gameCanvas {',
'      display: block;',
'      width: 480px; height: 800px;',
'      max-height: 90vh; max-width: 95vw;',
'      aspect-ratio: 480 / 800;',
'      box-shadow: 0 0 40px rgba(99, 102, 241, 0.25),',
'                  0 0 80px rgba(168, 85, 247, 0.15),',
'                  0 20px 50px rgba(0, 0, 0, 0.8);',
'      border-radius: 12px;',
'      border: 1px solid rgba(255, 255, 255, 0.12);',
'      background: #143621;',
'    }',
'    #soundBtn {',
'      position: absolute; top: 45px; right: 12px;',
'      background: rgba(15, 23, 42, 0.75); backdrop-filter: blur(8px);',
'      border: 1px solid rgba(255, 255, 255, 0.2);',
'      color: #f8fafc; font-size: 18px; width: 38px; height: 38px;',
'      border-radius: 50%; cursor: pointer; display: flex; align-items: center; justify-content: center;',
'      transition: all 0.2s ease; z-index: 10; box-shadow: 0 4px 12px rgba(0,0,0,0.3);',
'    }',
'    #soundBtn:hover { transform: scale(1.1); background: rgba(30, 41, 59, 0.9); border-color: #38bdf8; }',
'    #soundBtn:active { transform: scale(0.95); }',
'    #hint {',
'      color: rgba(255,255,255,0.7); font-size: 12px; line-height: 1.7;',
'      margin-top: 10px; text-align: center; font-family: "Roboto Mono", monospace; max-width: 520px;',
'    }',
'    kbd {',
'      background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.25);',
'      border-radius: 4px; padding: 2px 6px; font-size: 11px; color: #38bdf8; font-weight: bold;',
'    }',
'  </style>',
'</head>',
'<body>',
'  <div class="game-container">',
'    <button id="soundBtn" title="Toggle Sound">🔊</button>',
'    <canvas id="gameCanvas" width="480" height="800"></canvas>',
'  </div>',
'  <p id="hint">',
'    <kbd>1</kbd>-<kbd>0</kbd>/<kbd>-</kbd>/<kbd>=</kbd> Pick Card &bull;',
'    <kbd>H</kbd> Hero Ultimate &bull; <kbd>C</kbd> Cycle Hero &bull; <kbd>E</kbd> Claim Perk &bull;',
'    <kbd>D</kbd> Deck Mode (4+1 Pro vs 12 Master) &bull; <kbd>M</kbd> Mode &bull; <kbd>T</kbd> Theme',
'  </p>',
'<script>',
)

# ── JavaScript ───────────────────────────────────────────────────────────────
w(
'/* ============================================================',
'   ROYAL CLASH ULTIMATE  --  Phase 3 "Beyond Clash Royale" HTML5 Port',
'   Featuring: Hero Commanders, Roguelike Perks, 12 Cards (Inferno Dragon & Mega Knight),',
'   Pro Deck Cycling Mode, Night Weather & Lightning, and MVP Analytics!',
'   ============================================================ */',
'',
'// ============================================================',
'// 1. CONSTANTS & ARENA THEMES',
'// ============================================================',
'const SCREEN_W = 480, SCREEN_H = 800;',
'const FPS_MAX_DT = 1 / 30;',
'',
'const RIVER_TOP    = SCREEN_H / 2 - 30;',
'const RIVER_BOTTOM = SCREEN_H / 2 + 30;',
'const RIVER_MID    = SCREEN_H / 2;',
'const BRIDGE_LEFT_X  = SCREEN_W / 4;',
'const BRIDGE_RIGHT_X = 3 * SCREEN_W / 4;',
'const BRIDGE_W       = 60;',
'const AI_HALF_TOP    = 20;',
'const AI_HALF_BOTTOM = RIVER_TOP;',
'',
'const ELIXIR_MAX        = 10;',
'const ELIXIR_START      = 5;',
'const ELIXIR_REGEN_RATE = 1.0 / 1.4;',
'',
'const THEMES = [',
'  { name: "🌲 Forest Arena",   bg: "#143621", river: "#1e6f9f", bridge: "#a88850", nightBg: "#0a1812", nightRiver: "#0f3c5a" },',
'  { name: "🌋 Volcano Arena",  bg: "#270e0e", river: "#dc2626", bridge: "#3f3f46", nightBg: "#140606", nightRiver: "#b41414" },',
'  { name: "❄️ Glacier Arena",  bg: "#1e293b", river: "#0284c7", bridge: "#cbd5e1", nightBg: "#0f1723", nightRiver: "#02508c" },',
'];',
'',
'const CONFIG = {',
'  KingTower:     { hp: 3000, damage: 95,  attackRange: 135, attackCooldown: 1.1, width: 64, height: 64 },',
'  PrincessTower: { hp: 1700, damage: 58,  attackRange: 165, attackCooldown: 0.8, width: 46, height: 46 },',
'  Knight:   { hp: 700,  damage: 85,  speed: 90,  attackRange: 28,  attackCooldown: 1.0, radius: 16, elixirCost: 3 },',
'  Archer:   { hp: 270,  damage: 55,  speed: 75,  attackRange: 130, attackCooldown: 0.9, radius: 12, elixirCost: 3 },',
'  Giant:    { hp: 2200, damage: 130, speed: 45,  attackRange: 32,  attackCooldown: 1.5, radius: 22, elixirCost: 5 },',
'  Wizard:   { hp: 350,  damage: 95,  speed: 68,  attackRange: 115, attackCooldown: 1.4, radius: 14, elixirCost: 4, splashRadius: 55 },',
'  Skeleton: { hp: 65,   damage: 45,  speed: 110, attackRange: 22,  attackCooldown: 0.7, radius: 9,  elixirCost: 3, swarmCount: 4 },',
'  Valkyrie: { hp: 1150, damage: 110, speed: 70,  attackRange: 35,  attackCooldown: 1.2, radius: 18, elixirCost: 4, whirlwindRadius: 50 },',
'  Prince:   { hp: 1300, damage: 180, speed: 75,  attackRange: 30,  attackCooldown: 1.4, radius: 18, elixirCost: 5, chargeMult: 2.5 },',
'  Cannon:   { hp: 900,  damage: 75,  attackRange: 155, attackCooldown: 0.7, radius: 20, elixirCost: 3, isBuilding: true, lifetime: 30.0 },',
'  Fireball: { damage: 260, radius: 75, elixirCost: 4, isSpell: true },',
'  Freeze:   { radius: 85, duration: 3.5, elixirCost: 3, isSpell: true },',
'  InfDragon:{ hp: 950,  damage: 35,  speed: 65,  attackRange: 105, attackCooldown: 0.3, radius: 18, elixirCost: 4, isAir: true },',
'  MegaKnight:{hp: 2500, damage: 145, speed: 60,  attackRange: 34,  attackCooldown: 1.5, radius: 24, elixirCost: 6, splashRadius: 60 },',
'};',
'',
'const C = {',
'  PLAYER:   "#3b82f6",  PLAYER_D: "#1d4ed8",',
'  AI:       "#ef4444",  AI_D:     "#b91c1c",',
'  HP_OK:    "#22c55e",  HP_WARN:  "#eab308", HP_LOW: "#ef4444",',
'  ELIXIR:   "#d946ef",  ELIX_BG:  "#3b0764",',
'  WHITE:    "#ffffff",  BLACK:    "#000000",',
'  GOLD:     "#facc15",  RED:      "#ff0000",',
'  SPELL:    "#ff781f",  CYAN:     "#38bdf8",',
'  FREEZE:   "#bae6fd",  RAGE:     "#f43f5e", HEAL: "#4ade80",',
'  INVULN:   "#fde047",  PURPLE:   "#d946ef",',
'};',
'',
'const STATE_PLAYING   = "PLAYING";',
'const STATE_GAME_OVER = "GAME_OVER";',
'',
'const hypot = Math.hypot;',
'function randInt(a, b)    { return Math.floor(Math.random() * (b - a + 1)) + a; }',
'function randFloat(a, b)  { return Math.random() * (b - a) + a; }',
'function pick(arr)        { return arr[Math.floor(Math.random() * arr.length)]; }',
'function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }',
'',
'function rrect(ctx, x, y, w, h, r) {',
'  ctx.beginPath();',
'  ctx.moveTo(x + r, y);',
'  ctx.lineTo(x + w - r, y); ctx.quadraticCurveTo(x+w, y,   x+w, y+r);',
'  ctx.lineTo(x + w, y+h-r); ctx.quadraticCurveTo(x+w, y+h, x+w-r, y+h);',
'  ctx.lineTo(x + r, y + h); ctx.quadraticCurveTo(x,   y+h, x,   y+h-r);',
'  ctx.lineTo(x, y + r);     ctx.quadraticCurveTo(x,   y,   x+r, y);',
'  ctx.closePath();',
'}',
'',
'// ============================================================',
'// 2. ENHANCED WEB AUDIO API ENGINE',
'// ============================================================',
'class SoundFX {',
'  constructor() { this.ctx = null; this.enabled = true; }',
'  init() {',
'    if (!this.ctx) {',
'      const AudioCtx = window.AudioContext || window.webkitAudioContext;',
'      if (AudioCtx) this.ctx = new AudioCtx();',
'    }',
'    if (this.ctx && this.ctx.state === "suspended") this.ctx.resume();',
'  }',
'  toggle() {',
'    this.enabled = !this.enabled;',
'    document.getElementById("soundBtn").textContent = this.enabled ? "🔊" : "🔇";',
'  }',
'  playTone(freq, type, duration, gainVal = 0.1, freqEnd = null) {',
'    if (!this.enabled || !this.ctx) return;',
'    try {',
'      const osc = this.ctx.createOscillator(), gain = this.ctx.createGain();',
'      osc.type = type; osc.frequency.setValueAtTime(freq, this.ctx.currentTime);',
'      if (freqEnd !== null) osc.frequency.exponentialRampToValueAtTime(Math.max(1, freqEnd), this.ctx.currentTime + duration);',
'      gain.gain.setValueAtTime(gainVal, this.ctx.currentTime);',
'      gain.gain.exponentialRampToValueAtTime(0.001, this.ctx.currentTime + duration);',
'      osc.connect(gain); gain.connect(this.ctx.destination);',
'      osc.start(); osc.stop(this.ctx.currentTime + duration);',
'    } catch(e) {}',
'  }',
'  playNoise(duration, gainVal = 0.08, isBrown = false) {',
'    if (!this.enabled || !this.ctx) return;',
'    try {',
'      const bs = this.ctx.sampleRate * duration;',
'      const buf = this.ctx.createBuffer(1, bs, this.ctx.sampleRate);',
'      const data = buf.getChannelData(0);',
'      let lastOut = 0.0;',
'      for (let i = 0; i < bs; i++) {',
'        const white = Math.random() * 2 - 1;',
'        if (isBrown) { lastOut = (lastOut + 0.02 * white) / 1.02; data[i] = lastOut * 3.5; }',
'        else { data[i] = white; }',
'      }',
'      const noise = this.ctx.createBufferSource(); noise.buffer = buf;',
'      const gain = this.ctx.createGain();',
'      gain.gain.setValueAtTime(gainVal, this.ctx.currentTime);',
'      gain.gain.exponentialRampToValueAtTime(0.001, this.ctx.currentTime + duration);',
'      noise.connect(gain); gain.connect(this.ctx.destination);',
'      noise.start();',
'    } catch(e) {}',
'  }',
'  playSelect()     { this.playTone(520, "sine", 0.12, 0.08, 680); }',
'  playDeploy()     { this.playTone(320, "triangle", 0.2, 0.1, 160); this.playNoise(0.15, 0.05); }',
'  playAttack(kind) {',
'    if (kind === "arrow")    { this.playNoise(0.08, 0.06); this.playTone(700, "sine", 0.1, 0.05, 300); }',
'    else if (kind === "fireball") { this.playTone(180, "sawtooth", 0.25, 0.08, 50); this.playNoise(0.2, 0.07, true); }',
'    else if (kind === "cannon")   { this.playTone(150, "square", 0.15, 0.1, 40); this.playNoise(0.12, 0.08, true); }',
'    else                     { this.playTone(280, "triangle", 0.1, 0.08, 90); }',
'  }',
'  playHit()        { this.playNoise(0.06, 0.05); this.playTone(120, "square", 0.08, 0.06, 40); }',
'  playExplosion()  { this.playTone(100, "sawtooth", 0.5, 0.15, 20); this.playNoise(0.5, 0.18, true); }',
'  playFreeze()     { this.playTone(800, "sine", 0.35, 0.08, 1400); this.playNoise(0.25, 0.05); }',
'  playCharge()     { this.playTone(140, "square", 0.25, 0.12, 50); this.playTone(280, "sawtooth", 0.2, 0.08, 80); }',
'  playWhirlwind()  { this.playTone(200, "triangle", 0.2, 0.1, 450); }',
'  playRunePickup() { [523.25, 659.25, 783.99, 1046.50].forEach((f, i) => setTimeout(() => this.playTone(f, "sine", 0.25, 0.08), i*60)); }',
'  playHeroSkill()  { [261.63, 329.63, 392.00, 523.25, 659.25, 783.99].forEach((f, i) => setTimeout(() => this.playTone(f, "triangle", 0.35, 0.1), i*60)); this.playNoise(0.4, 0.08); }',
'  playPerkUnlock() { [587.33, 739.99, 880.00, 1174.66].forEach((f, i) => setTimeout(() => this.playTone(f, "sine", 0.3, 0.1), i*80)); }',
'  playMegaLanding() { this.playTone(90, "square", 0.5, 0.18, 25); this.playNoise(0.6, 0.22, true); }',
'  playThunder()    { this.playNoise(0.8, 0.12, true); this.playTone(70, "sawtooth", 0.6, 0.08, 20); }',
'  playDoubleElixir() { [261.63, 329.63, 392.00, 523.25, 659.25, 783.99].forEach((f, i) => setTimeout(() => this.playTone(f, "sine", 0.3, 0.08), i*80)); }',
'  playVictory()    { [523.25, 659.25, 783.99, 1046.50].forEach((f, i) => setTimeout(() => this.playTone(f, "triangle", 0.4, 0.12), i*120)); }',
'  playDefeat()     { [392.00, 349.23, 311.13, 261.63].forEach((f, i) => setTimeout(() => this.playTone(f, "sawtooth", 0.4, 0.1), i*140)); }',
'}',
'const sfx = new SoundFX();',
'document.getElementById("soundBtn").addEventListener("click", () => { sfx.init(); sfx.toggle(); });',
'',
'// ============================================================',
'// 3. VFX: PARTICLES, FLOATING TEXT & PROJECTILES',
'// ============================================================',
'class Particle {',
'  constructor(x, y, vx, vy, color, radius, life) {',
'    this.x = x; this.y = y; this.vx = vx; this.vy = vy;',
'    this.color = color; this.radius = radius;',
'    this.life = life; this.maxLife = life;',
'  }',
'  update(dt) {',
'    this.x += this.vx * dt; this.y += this.vy * dt;',
'    this.radius = Math.max(0.2, this.radius * (1 - 1.5 * dt));',
'    this.life -= dt;',
'    return this.life > 0;',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (this.radius <= 0.5 || this.life <= 0) return;',
'    ctx.fillStyle = this.color;',
'    ctx.beginPath(); ctx.arc(this.x + ox, this.y + oy, this.radius, 0, Math.PI*2); ctx.fill();',
'  }',
'}',
'',
'class FloatingText {',
'  constructor(x, y, text, color, isBig = false, life = 0.8) {',
'    this.x = x; this.y = y; this.text = text; this.color = color;',
'    this.isBig = isBig; this.life = life; this.maxLife = life;',
'    this.vy = -45;',
'  }',
'  update(dt) {',
'    this.y += this.vy * dt; this.life -= dt;',
'    return this.life > 0;',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (this.life <= 0) return;',
'    const alpha = Math.max(0, Math.min(1, this.life / this.maxLife));',
'    ctx.save(); ctx.globalAlpha = alpha;',
'    ctx.fillStyle = this.color;',
'    ctx.font = this.isBig ? "bold 28px Cinzel, monospace" : "bold 15px Outfit, monospace";',
'    ctx.textAlign = "center"; ctx.textBaseline = "middle";',
'    ctx.shadowColor = "rgba(0,0,0,0.8)"; ctx.shadowBlur = 6;',
'    ctx.fillText(this.text, this.x + ox, this.y + oy);',
'    ctx.restore();',
'  }',
'}',
'',
'class Projectile {',
'  constructor(x, y, tx, ty, speed, damage, splashRadius, team, kind, targetEntity = null, sourceEntity = null) {',
'    this.x = x; this.y = y; this.tx = tx; this.ty = ty;',
'    this.speed = speed; this.damage = damage;',
'    this.splashRadius = splashRadius; this.team = team;',
'    this.kind = kind; this.targetEntity = targetEntity;',
'    this.sourceEntity = sourceEntity; this.alive = true;',
'  }',
'  update(dt, enemies, particles, floatingTexts) {',
'    if (!this.alive) return;',
'    if (this.targetEntity && this.targetEntity.alive) {',
'      this.tx = this.targetEntity.x; this.ty = this.targetEntity.y;',
'    }',
'    const dx = this.tx - this.x, dy = this.ty - this.y;',
'    const dist = hypot(dx, dy);',
'    const step = this.speed * dt;',
'    if (dist <= step || dist < 10) {',
'      this.x = this.tx; this.y = this.ty;',
'      this._explode(enemies, particles, floatingTexts);',
'      this.alive = false;',
'    } else {',
'      this.x += (dx / dist) * step; this.y += (dy / dist) * step;',
'      if (Math.random() < 0.6) {',
'        const col = (this.kind === "fireball" || this.kind === "meteor") ? C.SPELL : C.WHITE;',
'        particles.push(new Particle(this.x, this.y, randFloat(-15,15), randFloat(-15,15), col, this.kind === "arrow" ? 2 : 4, 0.25));',
'      }',
'    }',
'  }',
'  _explode(enemies, particles, floatingTexts) {',
'    if (this.kind === "fireball" || this.kind === "meteor" || this.splashRadius > 0) {',
'      if (this.kind === "meteor" || this.kind === "fireball") sfx.playExplosion();',
'      const sr = Math.max(this.splashRadius, 40);',
'      for (const e of enemies) {',
'        if (!e.alive) continue;',
'        const d = hypot(e.x - this.x, e.y - this.y);',
'        if (d <= sr) {',
'          const dmg = d <= sr * 0.6 ? this.damage : Math.floor(this.damage * 0.7);',
'          e.takeDamage(dmg, floatingTexts, particles, this.sourceEntity);',
'        }',
'      }',
'      const cnt = this.kind === "meteor" ? 28 : 16;',
'      for (let i = 0; i < cnt; i++) {',
'        const ang = Math.random() * Math.PI * 2, spd = randFloat(30, 150);',
'        const col = pick([C.GOLD, C.SPELL, C.RED]);',
'        particles.push(new Particle(this.x, this.y, Math.cos(ang)*spd, Math.sin(ang)*spd, col, randFloat(4, 9), 0.5));',
'      }',
'    } else {',
'      sfx.playHit();',
'      if (this.targetEntity && this.targetEntity.alive) {',
'        this.targetEntity.takeDamage(this.damage, floatingTexts, particles, this.sourceEntity);',
'      } else if (enemies.length) {',
'        let best = null, bd = Infinity;',
'        for (const e of enemies) {',
'          if (!e.alive) continue;',
'          const d = hypot(e.x - this.x, e.y - this.y);',
'          if (d < bd) { best = e; bd = d; }',
'        }',
'        if (best && bd <= 40) best.takeDamage(this.damage, floatingTexts, particles, this.sourceEntity);',
'      }',
'    }',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (!this.alive) return;',
'    const ix = this.x + ox, iy = this.y + oy;',
'    ctx.save();',
'    if (this.kind === "meteor") {',
'      ctx.fillStyle = C.GOLD; ctx.beginPath(); ctx.arc(ix, iy, 14, 0, Math.PI*2); ctx.fill();',
'      ctx.fillStyle = C.SPELL; ctx.beginPath(); ctx.arc(ix, iy, 10, 0, Math.PI*2); ctx.fill();',
'    } else if (this.kind === "fireball") {',
'      ctx.fillStyle = C.SPELL; ctx.beginPath(); ctx.arc(ix, iy, 8, 0, Math.PI*2); ctx.fill();',
'      ctx.fillStyle = C.GOLD; ctx.beginPath(); ctx.arc(ix, iy, 5, 0, Math.PI*2); ctx.fill();',
'    } else if (this.kind === "arrow") {',
'      ctx.fillStyle = C.WHITE; ctx.beginPath(); ctx.arc(ix, iy, 3, 0, Math.PI*2); ctx.fill();',
'    } else {',
'      ctx.fillStyle = C.BLACK; ctx.beginPath(); ctx.arc(ix, iy, 5, 0, Math.PI*2); ctx.fill();',
'      ctx.fillStyle = C.GOLD; ctx.beginPath(); ctx.arc(ix, iy, 3, 0, Math.PI*2); ctx.fill();',
'    }',
'    ctx.restore();',
'  }',
'}',
'',
'// ============================================================',
'// 4. BATTLEFIELD RUNES / SHRINES',
'// ============================================================',
'class Rune {',
'  constructor(x, y, kind) {',
'    this.x = x; this.y = y; this.kind = kind; this.radius = 18;',
'    this.alive = true; this.time = 0;',
'  }',
'  update(dt, allUnits, particles, floatingTexts) {',
'    if (!this.alive) return;',
'    this.time += dt;',
'    if (Math.random() < 0.4) {',
'      const col = this.kind === "rage" ? C.RAGE : C.HEAL;',
'      particles.push(new Particle(this.x + randFloat(-10,10), this.y + randFloat(-10,10), 0, -20, col, 3, 0.4));',
'    }',
'    for (const u of allUnits) {',
'      if (!u.alive) continue;',
'      if (hypot(u.x - this.x, u.y - this.y) <= this.radius + u.radius) {',
'        this.alive = false; sfx.playRunePickup();',
'        const col = this.kind === "rage" ? C.RAGE : C.HEAL;',
'        const msg = this.kind === "rage" ? "⚡ RAGE +50%!" : "💖 HEAL +350!";',
'        floatingTexts.push(new FloatingText(this.x, this.y - 15, msg, col, true, 1.2));',
'        for (const ally of allUnits) {',
'          if (ally.alive && ally.team === u.team && hypot(ally.x - this.x, ally.y - this.y) <= 90) {',
'            if (this.kind === "rage") ally.rageTimer = Math.max(ally.rageTimer, 6.0);',
'            else { ally.hp = Math.min(ally.maxHp, ally.hp + 350); floatingTexts.push(new FloatingText(ally.x, ally.y - 20, "+350", C.HEAL, false)); }',
'          }',
'        }',
'        for (let i = 0; i < 25; i++) {',
'          const ang = Math.random() * Math.PI * 2, spd = randFloat(40, 120);',
'          particles.push(new Particle(this.x, this.y, Math.cos(ang)*spd, Math.sin(ang)*spd, col, 5, 0.6));',
'        }',
'        break;',
'      }',
'    }',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (!this.alive) return;',
'    const ix = this.x + ox, iy = this.y + oy;',
'    const col = this.kind === "rage" ? C.RAGE : C.HEAL;',
'    const r = this.radius + 3 * Math.sin(this.time * 6);',
'    ctx.strokeStyle = col; ctx.lineWidth = 2;',
'    ctx.beginPath(); ctx.arc(ix, iy, r, 0, Math.PI*2); ctx.stroke();',
'    ctx.fillStyle = Math.floor(this.time * 4) % 2 === 0 ? C.WHITE : col;',
'    ctx.beginPath(); ctx.arc(ix, iy, this.radius * 0.6, 0, Math.PI*2); ctx.fill();',
'  }',
'}',
'',
'// ============================================================',
'// 5. BASE ENTITY (WITH STATS & PERKS)',
'// ============================================================',
'class Entity {',
'  constructor(x, y, hp, team) {',
'    this.x = x; this.y = y; this.hp = hp; this.maxHp = hp;',
'    this.team = team; this.alive = true;',
'    this.freezeTimer = 0.0; this.rageTimer = 0.0; this.invulnTimer = 0.0;',
'    this.damageDealt = 0; this.kills = 0; this.kindName = "Unit";',
'  }',
'  get color() {',
'    if (this.invulnTimer > 0) return C.INVULN;',
'    if (this.freezeTimer > 0) return C.FREEZE;',
'    return this.team === "player" ? C.PLAYER : C.AI;',
'  }',
'  get darkColor() { return this.team === "player" ? C.PLAYER_D : C.AI_D; }',
'',
'  takeDamage(amt, floatingTexts = null, particles = null, sourceEntity = null) {',
'    if (!this.alive || this.invulnTimer > 0) return;',
'    this.hp = Math.max(0, this.hp - amt);',
'    if (sourceEntity) {',
'      sourceEntity.damageDealt += Math.floor(amt);',
'      if (sourceEntity.hasVampiric) sourceEntity.hp = Math.min(sourceEntity.maxHp, sourceEntity.hp + amt * 0.25);',
'    }',
'    if (this.hp <= 0) {',
'      this.alive = false;',
'      if (sourceEntity) sourceEntity.kills++;',
'      if (particles) {',
'        for (let i = 0; i < 14; i++) {',
'          const ang = Math.random() * Math.PI * 2, spd = randFloat(20, 80);',
'          particles.push(new Particle(this.x, this.y, Math.cos(ang)*spd, Math.sin(ang)*spd, this.color, randFloat(3, 7), 0.4));',
'        }',
'      }',
'      if (this.hasExplosive && particles) {',
'        for (let i = 0; i < 20; i++) {',
'          const ang = Math.random() * Math.PI * 2, spd = randFloat(30, 100);',
'          particles.push(new Particle(this.x, this.y, Math.cos(ang)*spd, Math.sin(ang)*spd, C.SPELL, 5, 0.4));',
'        }',
'      }',
'    }',
'    if (floatingTexts) {',
'      const col = amt > 120 ? C.GOLD : C.WHITE;',
'      floatingTexts.push(new FloatingText(this.x + randInt(-10,10), this.y - 20, `-${Math.floor(amt)}`, col, amt > 120));',
'    }',
'    if (particles && Math.random() < 0.7) {',
'      particles.push(new Particle(this.x, this.y, randFloat(-30,30), randFloat(-30,30), C.GOLD, 4, 0.2));',
'    }',
'  }',
'  hpFrac() { return this.maxHp > 0 ? Math.max(0, this.hp / this.maxHp) : 0; }',
'  hpBarColor() {',
'    const f = this.hpFrac();',
'    return f > 0.6 ? C.HP_OK : f > 0.3 ? C.HP_WARN : C.HP_LOW;',
'  }',
'  drawHpBar(ctx, bx, by, bw = 40, bh = 5) {',
'    ctx.fillStyle = C.BLACK; ctx.fillRect(bx, by, bw, bh);',
'    const filled = Math.floor(bw * this.hpFrac());',
'    if (filled > 0) { ctx.fillStyle = this.hpBarColor(); ctx.fillRect(bx, by, filled, bh); }',
'    ctx.strokeStyle = C.WHITE; ctx.lineWidth = 1;',
'    ctx.strokeRect(bx + 0.5, by + 0.5, bw, bh);',
'  }',
'}',
'',
'// ============================================================',
'// 6. TOWERS & BUILDINGS',
'// ============================================================',
'class Tower extends Entity {',
'  constructor(x, y, kind, team) {',
'    const c = CONFIG[kind];',
'    super(x, y, c.hp, team);',
'    this.kind = kind; this.kindName = kind; this.damage = c.damage;',
'    this.attackRange = c.attackRange; this.attackCooldown = c.attackCooldown;',
'    this.width = c.width; this.height = c.height; this.attackTimer = 0;',
'    this.hasTwin = false;',
'  }',
'  get rect() {',
'    return { left: this.x - this.width/2, top: this.y - this.height/2, right: this.x + this.width/2, bottom: this.y + this.height/2 };',
'  }',
'  update(dt, enemies, projectiles) {',
'    if (!this.alive) return;',
'    if (this.invulnTimer > 0) this.invulnTimer -= dt;',
'    if (this.freezeTimer > 0) { this.freezeTimer -= dt; return; }',
'    if (this.rageTimer > 0)   this.rageTimer -= dt;',
'    const cdMult = this.rageTimer > 0 ? 0.65 : 1.0;',
'    this.attackTimer = Math.max(0, this.attackTimer - dt);',
'    if (this.attackTimer === 0) {',
'      const t = this._nearestInRange(enemies);',
'      if (t) {',
'        const kind = this.kind === "KingTower" ? "cannon" : "arrow";',
'        const spd  = kind === "cannon" ? 450 : 500;',
'        projectiles.push(new Projectile(this.x, this.y, t.x, t.y, spd, this.damage, 0, this.team, kind, t, this));',
'        if (this.hasTwin && this.kind === "PrincessTower") {',
'          projectiles.push(new Projectile(this.x+10, this.y, t.x, t.y, spd*1.05, this.damage, 0, this.team, kind, t, this));',
'        }',
'        sfx.playAttack(kind);',
'        this.attackTimer = this.attackCooldown * cdMult;',
'      }',
'    }',
'  }',
'  _nearestInRange(enemies) {',
'    let best = null, bd = Infinity;',
'    for (const e of enemies) {',
'      if (!e.alive) continue;',
'      const d = hypot(e.x - this.x, e.y - this.y);',
'      if (d <= this.attackRange && d < bd) { best = e; bd = d; }',
'    }',
'    return best;',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (!this.alive) return;',
'    const r = { left: this.rect.left + ox, top: this.rect.top + oy, width: this.width, height: this.height };',
'    ctx.fillStyle = this.darkColor;',
'    rrect(ctx, r.left - 2, r.top - 2, r.width + 4, r.height + 4, 6); ctx.fill();',
'    ctx.fillStyle = this.color;',
'    rrect(ctx, r.left, r.top, r.width, r.height, 6); ctx.fill();',
'    if (this.invulnTimer > 0 || this.rageTimer > 0) {',
'      ctx.strokeStyle = this.invulnTimer > 0 ? C.INVULN : C.RAGE; ctx.lineWidth = 2;',
'      rrect(ctx, r.left-4, r.top-4, r.width+8, r.height+8, 8); ctx.stroke();',
'    }',
'    ctx.fillStyle = C.WHITE; ctx.font = "bold 15px Cinzel, monospace";',
'    ctx.textAlign = "center"; ctx.textBaseline = "middle";',
'    ctx.fillText(this.kind === "KingTower" ? "K" : "P", this.x + ox, this.y + oy);',
'    this.drawHpBar(ctx, r.left, r.top - 10, r.width, 6);',
'  }',
'}',
'class KingTower     extends Tower { constructor(x,y,t){ super(x,y,"KingTower",    t); } }',
'class PrincessTower extends Tower { constructor(x,y,t){ super(x,y,"PrincessTower",t); } }',
'',
'class CannonBuilding extends Entity {',
'  constructor(x, y, team) {',
'    const c = CONFIG.Cannon;',
'    super(x, y, c.hp, team);',
'    this.kind = "Cannon"; this.kindName = "Cannon"; this.damage = c.damage;',
'    this.attackRange = c.attackRange; this.attackCooldown = c.attackCooldown;',
'    this.radius = c.radius; this.lifetime = c.lifetime; this.attackTimer = 0;',
'  }',
'  get rect() {',
'    return { left: this.x - this.radius, top: this.y - this.radius, right: this.x + this.radius, bottom: this.y + this.radius };',
'  }',
'  update(dt, enemies, projectiles) {',
'    if (!this.alive) return;',
'    this.hp -= this.maxHp * (dt / this.lifetime);',
'    if (this.hp <= 0) { this.alive = false; return; }',
'    if (this.invulnTimer > 0) this.invulnTimer -= dt;',
'    if (this.freezeTimer > 0) { this.freezeTimer -= dt; return; }',
'    if (this.rageTimer > 0)   this.rageTimer -= dt;',
'    const cdMult = this.rageTimer > 0 ? 0.65 : 1.0;',
'    this.attackTimer = Math.max(0, this.attackTimer - dt);',
'    if (this.attackTimer === 0) {',
'      let best = null, bd = Infinity;',
'      for (const e of enemies) {',
'        if (!e.alive) continue;',
'        const d = hypot(e.x - this.x, e.y - this.y);',
'        if (d <= this.attackRange && d < bd) { best = e; bd = d; }',
'      }',
'      if (best) {',
'        projectiles.push(new Projectile(this.x, this.y, best.x, best.y, 500, this.damage, 0, this.team, "cannon", best, this));',
'        sfx.playAttack("cannon");',
'        this.attackTimer = this.attackCooldown * cdMult;',
'      }',
'    }',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (!this.alive) return;',
'    const ix = this.x + ox, iy = this.y + oy;',
'    ctx.fillStyle = "#475569"; ctx.beginPath(); ctx.arc(ix, iy, this.radius+2, 0, Math.PI*2); ctx.fill();',
'    ctx.fillStyle = this.color; ctx.beginPath(); ctx.arc(ix, iy, this.radius, 0, Math.PI*2); ctx.fill();',
'    if (this.rageTimer > 0) { ctx.strokeStyle = C.RAGE; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(ix, iy, this.radius+4, 0, Math.PI*2); ctx.stroke(); }',
'    ctx.fillStyle = C.WHITE; ctx.font = "bold 11px Outfit, monospace";',
'    ctx.textAlign = "center"; ctx.textBaseline = "middle";',
'    ctx.fillText("CAN", ix, iy);',
'    this.drawHpBar(ctx, ix - 18, iy - this.radius - 10, 36, 5);',
'  }',
'}',
'',
'// ============================================================',
'// 7. UNITS & LEGENDARIES',
'// ============================================================',
'class Unit extends Entity {',
'  static AGGRO_RANGE = 220;',
'  constructor(x, y, kind, team) {',
'    const c = CONFIG[kind];',
'    super(x, y, c.hp, team);',
'    this.kind = kind; this.kindName = kind; this.damage = c.damage; this.speed = c.speed;',
'    this.attackRange = c.attackRange; this.attackCooldown = c.attackCooldown;',
'    this.radius = c.radius; this.splashRadius = c.splashRadius || 0;',
'    this.whirlwindRadius = c.whirlwindRadius || 0; this.chargeMult = c.chargeMult || 1.0;',
'    this.isAir = c.isAir || false;',
'    this.attackTimer = 0; this.target = null;',
'    this.lane = x <= SCREEN_W / 2 ? 0 : 1;',
'    this.waypoints = this._buildWaypoints(team);',
'    this.wpIdx = 0;',
'    this.moveTimer = 0.0; this.isCharging = false;',
'    this.laserTime = 0.0; this.laserTarget = null;',
'    this.isSpawning = (kind === "MegaKnight");',
'    this.spawnTimer = this.isSpawning ? 0.6 : 0.0;',
'  }',
'  _buildWaypoints(team) {',
'    const bx = this.lane === 0 ? BRIDGE_LEFT_X : BRIDGE_RIGHT_X;',
'    return team === "player" ? [[bx, RIVER_BOTTOM - 15], [bx, RIVER_TOP + 15]] : [[bx, RIVER_TOP + 15], [bx, RIVER_BOTTOM - 15]];',
'  }',
'  _findTarget(enemyUnits, enemyTowers) {',
'    const u = this._nearestAlive(enemyUnits);',
'    if (u && hypot(u.x - this.x, u.y - this.y) <= Unit.AGGRO_RANGE) return u;',
'    return this._nearestAlive(enemyTowers);',
'  }',
'  _nearestAlive(entities) {',
'    let best = null, bd = Infinity;',
'    for (const e of entities) {',
'      if (!e.alive) continue;',
'      const d = hypot(e.x - this.x, e.y - this.y);',
'      if (d < bd) { best = e; bd = d; }',
'    }',
'    return best;',
'  }',
'  update(dt, enemyUnits, enemyTowers, allUnits, allTowers, projectiles, floatingTexts, particles) {',
'    if (!this.alive) return;',
'    if (this.invulnTimer > 0) this.invulnTimer -= dt;',
'    if (this.isSpawning) {',
'      this.spawnTimer -= dt;',
'      if (this.spawnTimer <= 0) {',
'        this.isSpawning = false; sfx.playMegaLanding();',
'        floatingTexts.push(new FloatingText(this.x, this.y - 20, "💥 MEGA LANDING!", C.GOLD, true, 1.2));',
'        for (const e of [...enemyUnits, ...enemyTowers]) {',
'          if (e.alive && hypot(e.x - this.x, e.y - this.y) <= 85) {',
'            e.takeDamage(180, floatingTexts, particles, this);',
'            e.freezeTimer = Math.max(e.freezeTimer, 1.5);',
'          }',
'        }',
'        for (let i = 0; i < 30; i++) {',
'          const ang = Math.random() * Math.PI * 2, spd = randFloat(40, 130);',
'          particles.push(new Particle(this.x, this.y, Math.cos(ang)*spd, Math.sin(ang)*spd, C.GOLD, 6, 0.5));',
'        }',
'      }',
'      return;',
'    }',
'    if (this.freezeTimer > 0) { this.freezeTimer -= dt; this.isCharging = false; this.moveTimer = 0.0; this.laserTime = 0.0; return; }',
'    if (this.rageTimer > 0)   this.rageTimer -= dt;',
'    const spdMult = (this.rageTimer > 0 ? 1.5 : 1.0) * (this.isCharging ? 1.6 : 1.0);',
'    const cdMult  = this.rageTimer > 0 ? 0.65 : 1.0;',
'',
'    if (this.target !== null && !this.target.alive) { this.target = null; this.laserTime = 0.0; this.laserTarget = null; }',
'    this.target = this._findTarget(enemyUnits, enemyTowers);',
'    this.attackTimer = Math.max(0, this.attackTimer - dt);',
'',
'    let moved = false;',
'    if (this.target !== null) {',
'      const dist = hypot(this.target.x - this.x, this.target.y - this.y);',
'      if (dist <= this.attackRange) {',
'        if (this.kind === "InfDragon") {',
'          if (this.laserTarget !== this.target) { this.laserTarget = this.target; this.laserTime = 0.0; }',
'          this.laserTime += dt;',
'        }',
'        if (this.attackTimer === 0) {',
'          this._performAttack(projectiles, floatingTexts, particles, enemyUnits, enemyTowers);',
'          this.attackTimer = this.attackCooldown * cdMult;',
'          this.isCharging = false; this.moveTimer = 0.0;',
'        }',
'      } else {',
'        moved = true; this.laserTime = 0.0; this.laserTarget = null;',
'        if (this.isAir) {',
'          this._moveToward(this.target.x, this.target.y, dt * spdMult);',
'        } else if (this.wpIdx < this.waypoints.length) {',
'          const [wx, wy] = this.waypoints[this.wpIdx];',
'          if (hypot(wx - this.x, wy - this.y) < 25) this.wpIdx++;',
'          else this._moveToward(wx, wy, dt * spdMult);',
'        } else {',
'          this._moveToward(this.target.x, this.target.y, dt * spdMult);',
'        }',
'      }',
'    }',
'',
'    if (moved && this.kind === "Prince") {',
'      this.moveTimer += dt;',
'      if (this.moveTimer >= 0.8 && !this.isCharging) {',
'        this.isCharging = true; sfx.playCharge();',
'        floatingTexts.push(new FloatingText(this.x, this.y - 15, "⚡ CHARGE!", C.GOLD, true));',
'      }',
'      if (this.isCharging && Math.random() < 0.6) {',
'        particles.push(new Particle(this.x, this.y, randFloat(-20,20), randFloat(-20,20), C.GOLD, 5, 0.3));',
'      }',
'    } else if (!moved) {',
'      this.isCharging = false; this.moveTimer = 0.0;',
'    }',
'',
'    if (!this.isAir && allTowers.length > 0) this._avoidTowers(allTowers, dt * spdMult);',
'    this._separate(allUnits);',
'  }',
'  _performAttack(projectiles, floatingTexts, particles, enemyUnits, enemyTowers) {',
'    if (!this.target || !this.target.alive) return;',
'    let dmg = Math.floor(this.damage * (this.isCharging ? this.chargeMult : 1.0));',
'    if (this.kind === "InfDragon") {',
'      const mult = 1.0 + Math.min(8.0, this.laserTime * 3.0);',
'      dmg = Math.floor(this.damage * mult);',
'      this.target.takeDamage(dmg, floatingTexts, particles, this);',
'      particles.push(new Particle(this.target.x, this.target.y, randFloat(-20,20), randFloat(-20,20), C.SPELL, 4, 0.2));',
'    } else if (this.kind === "Archer") {',
'      projectiles.push(new Projectile(this.x, this.y, this.target.x, this.target.y, 480, dmg, 0, this.team, "arrow", this.target, this));',
'      if (this.hasTwin) projectiles.push(new Projectile(this.x+8, this.y, this.target.x, this.target.y, 500, dmg, 0, this.team, "arrow", this.target, this));',
'      sfx.playAttack("arrow");',
'    } else if (this.kind === "Wizard") {',
'      projectiles.push(new Projectile(this.x, this.y, this.target.x, this.target.y, 420, dmg, this.splashRadius, this.team, "fireball", this.target, this));',
'      sfx.playAttack("fireball");',
'    } else if (this.kind === "Valkyrie" || this.kind === "MegaKnight") {',
'      sfx.playWhirlwind();',
'      const rad = this.kind === "Valkyrie" ? this.whirlwindRadius : this.splashRadius;',
'      for (const e of [...enemyUnits, ...enemyTowers]) {',
'        if (e.alive && hypot(e.x - this.x, e.y - this.y) <= rad) e.takeDamage(dmg, floatingTexts, particles, this);',
'      }',
'      for (let i = 0; i < 20; i++) {',
'        const ang = Math.random() * Math.PI * 2;',
'        particles.push(new Particle(this.x, this.y, Math.cos(ang)*110, Math.sin(ang)*110, C.GOLD, 4, 0.25));',
'      }',
'    } else {',
'      sfx.playAttack("melee");',
'      this.target.takeDamage(dmg, floatingTexts, particles, this);',
'      if (this.isCharging) {',
'        for (let i = 0; i < 15; i++) {',
'          const ang = Math.random() * Math.PI * 2;',
'          particles.push(new Particle(this.target.x, this.target.y, Math.cos(ang)*140, Math.sin(ang)*140, C.GOLD, 6, 0.4));',
'        }',
'      }',
'    }',
'  }',
'  _moveToward(tx, ty, dtSpeed) {',
'    const dx = tx - this.x, dy = ty - this.y, d = hypot(dx, dy);',
'    if (d < 0.5) return;',
'    this.x += (dx / d) * this.speed * dtSpeed; this.y += (dy / d) * this.speed * dtSpeed;',
'  }',
'  _separate(allUnits) {',
'    for (const o of allUnits) {',
'      if (o === this || !o.alive || (this.isAir !== o.isAir)) continue;',
'      const dx = this.x - o.x, dy = this.y - o.y, d = hypot(dx, dy), mn = this.radius + o.radius;',
'      if (d > 0.1 && d < mn) { const ov = (mn - d) / 2; this.x += (dx / d) * ov; this.y += (dy / d) * ov; }',
'    }',
'  }',
'  _avoidTowers(towers, dtSpeed) {',
'    const adist = this.radius + 40, aspeed = this.speed * 1.5;',
'    for (const t of towers) {',
'      if (!t.alive || t === this.target) continue;',
'      const r = t.rect;',
'      const cx = clamp(this.x, r.left, r.right), cy = clamp(this.y, r.top, r.bottom);',
'      const dx = this.x - cx, dy = this.y - cy, d = hypot(dx, dy);',
'      if (d > 0.1 && d < adist) { const str = (adist - d) / adist; this.x += (dx / d) * aspeed * str * dtSpeed; this.y += (dy / d) * aspeed * str * dtSpeed; }',
'    }',
'  }',
'  draw(ctx, ox = 0, oy = 0) {',
'    if (!this.alive) return;',
'    const ix = Math.round(this.x + ox), iy = Math.round(this.y + oy);',
'    if (this.isSpawning) {',
'      ctx.strokeStyle = C.GOLD; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(ix, iy, this.radius*2, 0, Math.PI*2); ctx.stroke();',
'      ctx.fillStyle = C.GOLD; ctx.font = "bold 11px Outfit, monospace"; ctx.textAlign = "center"; ctx.fillText("LEAPING...", ix, iy);',
'      return;',
'    }',
'    if (this.kind === "InfDragon" && this.laserTarget && this.laserTarget.alive && this.laserTime > 0) {',
'      const tp = { x: Math.round(this.laserTarget.x + ox), y: Math.round(this.laserTarget.y + oy) };',
'      ctx.strokeStyle = this.laserTime > 1.5 ? C.RED : C.SPELL;',
'      ctx.lineWidth = Math.min(8, 2 + Math.floor(this.laserTime * 2));',
'      ctx.beginPath(); ctx.moveTo(ix, iy); ctx.lineTo(tp.x, tp.y); ctx.stroke();',
'    }',
'    if (this.isCharging) { ctx.fillStyle = C.GOLD; ctx.beginPath(); ctx.arc(ix, iy, this.radius+4, 0, Math.PI*2); ctx.fill(); }',
'    ctx.fillStyle = this.darkColor; ctx.beginPath(); ctx.arc(ix+2, iy+2, this.radius, 0, Math.PI*2); ctx.fill();',
'    ctx.fillStyle = this.color; ctx.beginPath(); ctx.arc(ix, iy, this.radius, 0, Math.PI*2); ctx.fill();',
'    if (this.rageTimer > 0) { ctx.strokeStyle = C.RAGE; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(ix, iy, this.radius+3, 0, Math.PI*2); ctx.stroke(); }',
'    ctx.strokeStyle = C.WHITE; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(ix, iy, this.radius, 0, Math.PI*2); ctx.stroke();',
'    const fs = Math.max(10, Math.floor(this.radius * 1.2));',
'    ctx.fillStyle = C.WHITE; ctx.font = `bold ${fs}px Outfit, monospace`;',
'    ctx.textAlign = "center"; ctx.textBaseline = "middle";',
'    ctx.fillText(this.kind.slice(0, 2).toUpperCase(), ix, iy);',
'    this.drawHpBar(ctx, ix - this.radius, iy - this.radius - 10, this.radius*2, 4);',
'  }',
'}',
'class Knight   extends Unit { constructor(x,y,t){ super(x,y,"Knight",t);   } }',
'class Archer   extends Unit { constructor(x,y,t){ super(x,y,"Archer",t);   } }',
'class Giant    extends Unit { constructor(x,y,t){ super(x,y,"Giant",t);    } _findTarget(eu, et) { return this._nearestAlive(et); } }',
'class Wizard   extends Unit { constructor(x,y,t){ super(x,y,"Wizard",t);   } }',
'class Skeleton extends Unit { constructor(x,y,t){ super(x,y,"Skeleton",t); } }',
'class Valkyrie extends Unit { constructor(x,y,t){ super(x,y,"Valkyrie",t); } }',
'class Prince   extends Unit { constructor(x,y,t){ super(x,y,"Prince",t);   } }',
'class InfernoDragon extends Unit { constructor(x,y,t){ super(x,y,"InfDragon",t); } }',
'class MegaKnight   extends Unit { constructor(x,y,t){ super(x,y,"MegaKnight",t); } }',
'',
'// ============================================================',
'// 8. HERO COMMANDERS & PERKS',
'// ============================================================',
'class HeroCommander {',
'  static HEROES = ["PALADIN", "ARCHMAGE", "MECHA"];',
'  constructor(kind, team) {',
'    this.kind = kind; this.team = team; this.cdTimer = 0;',
'    this.maxCd = kind === "PALADIN" ? 25.0 : (kind === "ARCHMAGE" ? 30.0 : 28.0);',
'  }',
'  update(dt) { if (this.cdTimer > 0) this.cdTimer = Math.max(0, this.cdTimer - dt); }',
'  activateUltimate(game) {',
'    if (this.cdTimer > 0 || game.state !== STATE_PLAYING) return false;',
'    this.cdTimer = this.maxCd; sfx.playHeroSkill();',
'    game.showFlash(`👑 HERO ULTIMATE: ${this.kind}!`); game.screenShake = 0.4;',
'    const myU = this.team === "player" ? game.playerUnits : game.aiUnits;',
'    const myT = this.team === "player" ? game.playerTowers: game.aiTowers;',
'    const enU = this.team === "player" ? game.aiUnits     : game.playerUnits;',
'    const enT = this.team === "player" ? game.aiTowers    : game.playerTowers;',
'    if (this.kind === "PALADIN") {',
'      for (const u of [...myU, ...myT]) {',
'        u.invulnTimer = Math.max(u.invulnTimer, 3.0); u.hp = Math.min(u.maxHp, u.hp + 400);',
'        game.floatingTexts.push(new FloatingText(u.x, u.y - 25, "💖 +400 INVULN!", C.INVULN, true));',
'        for (let i = 0; i < 15; i++) { const ang = Math.random()*Math.PI*2, spd = randFloat(30,90); game.particles.push(new Particle(u.x, u.y, Math.cos(ang)*spd, Math.sin(ang)*spd, C.INVULN, 5, 0.5)); }',
'      }',
'    } else if (this.kind === "ARCHMAGE") {',
'      for (let i = 0; i < 8; i++) {',
'        const tx = randInt(40, SCREEN_W - 40);',
'        const ty = this.team === "player" ? randInt(20, RIVER_TOP) : randInt(RIVER_BOTTOM, SCREEN_H - 120);',
'        game.projectiles.push(new Projectile(tx, ty - 350, tx, ty, 650, 180, 55, this.team, "meteor"));',
'      }',
'    } else if (this.kind === "MECHA") {',
'      for (const t of enT) { t.freezeTimer = Math.max(t.freezeTimer, 4.0); game.floatingTexts.push(new FloatingText(t.x, t.y - 20, "⚡ EMP STUN!", C.CYAN, true)); }',
'      for (const u of myU) { u.rageTimer = Math.max(u.rageTimer, 5.0); game.floatingTexts.push(new FloatingText(u.x, u.y - 20, "⚡ OVERDRIVE!", C.RAGE, true)); }',
'    }',
'    return true;',
'  }',
'}',
'',
'class PerkManager {',
'  static PERKS = [',
'    ["💥 Explosive Demise", "EXPLOSIVE"], ["🧛 Vampiric Aura", "VAMPIRIC"],',
'    ["🏹 Twin Arrows", "TWIN_ARROWS"],     ["🛡️ Titan Skin", "TITAN_SKIN"],',
'    ["⚡ Elixir Overflow", "OVERFLOW"]',
'  ];',
'  constructor() { this.perksAcquired = new Set(); this.elixirCounter = 0; this.perksAvailable = 0; }',
'  addSpentElixir(amt) {',
'    this.elixirCounter += amt;',
'    if (this.elixirCounter >= 20.0) { this.elixirCounter -= 20.0; this.perksAvailable++; }',
'  }',
'  claimPerk(game) {',
'    if (this.perksAvailable <= 0) return false;',
'    const avail = PerkManager.PERKS.filter(p => !this.perksAcquired.has(p[1]));',
'    if (!avail.length) return false;',
'    const [name, code] = pick(avail);',
'    this.perksAcquired.add(code); this.perksAvailable--; sfx.playPerkUnlock();',
'    game.showFlash(`🌟 PERK UNLOCKED: ${name}!`);',
'    if (code === "TITAN_SKIN") {',
'      for (const u of game.playerUnits) if (["Giant","Knight","MegaKnight","Prince"].includes(u.kind)) { u.maxHp *= 1.4; u.hp *= 1.4; }',
'    } else if (code === "TWIN_ARROWS") {',
'      for (const t of game.playerTowers) t.hasTwin = true;',
'      for (const u of game.playerUnits) if (u.kind === "Archer") u.hasTwin = true;',
'    }',
'    return true;',
'  }',
'  applyToUnit(u) {',
'    if (this.perksAcquired.has("EXPLOSIVE")) u.hasExplosive = true;',
'    if (this.perksAcquired.has("VAMPIRIC"))  u.hasVampiric = true;',
'    if (this.perksAcquired.has("TWIN_ARROWS") && u.kind === "Archer") u.hasTwin = true;',
'    if (this.perksAcquired.has("TITAN_SKIN") && ["Giant","Knight","MegaKnight","Prince"].includes(u.kind)) { u.maxHp *= 1.4; u.hp *= 1.4; }',
'  }',
'}',
'',
'// ============================================================',
'// 9. AI CONTROLLER',
'// ============================================================',
'class AIController {',
'  constructor() { this.interval = 1.8; this.timer = this.interval; this.hero = new HeroCommander("ARCHMAGE", "ai"); }',
'  update(dt, elixir, spawnCb, spellCb, aiTowers, playerUnits, aiUnits, mode, game) {',
'    this.timer -= dt; this.hero.update(dt);',
'    if (this.hero.cdTimer === 0 && playerUnits.length >= 3 && Math.random() < 0.4) this.hero.activateUltimate(game);',
'    if (this.timer > 0) return elixir;',
'    this.timer = this.interval;',
'',
'    if (elixir >= 4 && playerUnits.length >= 3) {',
'      for (const pu of playerUnits) {',
'        const cluster = playerUnits.filter(u => hypot(u.x - pu.x, u.y - pu.y) <= 75);',
'        if (cluster.length >= 3 && Math.random() < 0.7) { spellCb("Fireball", pu.x, pu.y, "ai"); return elixir - 4; }',
'        else if (cluster.length >= 2 && elixir >= 3 && Math.random() < 0.4) { spellCb("Freeze", pu.x, pu.y, "ai"); return elixir - 3; }',
'      }',
'    }',
'    const invaders = playerUnits.filter(u => u.y < RIVER_BOTTOM + 50);',
'    if (invaders.length > 0) {',
'      invaders.sort((a,b) => a.y - b.y);',
'      const tu = invaders[0], lane = tu.x <= SCREEN_W / 2 ? 0 : 1;',
'      const bx = lane === 0 ? BRIDGE_LEFT_X : BRIDGE_RIGHT_X;',
'      if (["Giant", "Prince", "MegaKnight"].includes(tu.kind) && elixir >= 4) {',
'        if (Math.random() < 0.5) spawnCb("InfDragon", bx, AI_HALF_BOTTOM - 50, "ai", false);',
'        else spawnCb("Cannon", bx, AI_HALF_BOTTOM - 60, "ai", false);',
'        return elixir - 4;',
'      } else if (["Skeleton", "Archer"].includes(tu.kind) && elixir >= 4) {',
'        spawnCb("Valkyrie", bx, AI_HALF_BOTTOM - 50, "ai", false); return elixir - 4;',
'      }',
'    }',
'    const cards = [["Knight",3,false], ["Archer",3,false], ["Giant",5,false], ["Wizard",4,false], ["Skeleton",3,true], ["Valkyrie",4,false], ["Prince",5,false], ["Cannon",3,false], ["InfDragon",4,false], ["MegaKnight",6,false]];',
'    const aff = cards.filter(c => elixir >= c[1]);',
'    if (!aff.length || Math.random() > 0.65) return elixir;',
'    const chosen = pick(aff); const [sx, sy] = this._randomSpawn(aiTowers);',
'    spawnCb(chosen[0], sx, sy, "ai", chosen[2]); return elixir - chosen[1];',
'  }',
'  _randomSpawn(aiTowers) {',
'    for (let i = 0; i < 20; i++) {',
'      const x = randInt(40, SCREEN_W - 40), y = randInt(AI_HALF_TOP + 20, AI_HALF_BOTTOM - 30);',
'      if (aiTowers.every(t => !t.alive || !(x >= t.rect.left-10 && x <= t.rect.right+10 && y >= t.rect.top-10 && y <= t.rect.bottom+10))) return [x, y];',
'    }',
'    return [SCREEN_W / 2, (AI_HALF_TOP + AI_HALF_BOTTOM) / 2];',
'  }',
'}',
'',
'// ============================================================',
'// 10. GAME STATE MANAGER',
'// ============================================================',
'class GameState {',
'  constructor() {',
'    this.CARDS = [',
'      ["Knight",    Knight,         3, false, false],',
'      ["Archer",    Archer,         3, false, false],',
'      ["Giant",     Giant,          5, false, false],',
'      ["Wizard",    Wizard,         4, false, false],',
'      ["Skeleton",  Skeleton,       3, false, true ],',
'      ["Valkyrie",  Valkyrie,       4, false, false],',
'      ["Prince",    Prince,         5, false, false],',
'      ["Cannon",    CannonBuilding, 3, false, false],',
'      ["InfDragon", InfernoDragon,  4, false, false],',
'      ["MegaKnight",MegaKnight,     6, false, false],',
'      ["Fireball",  null,           4, true,  false],',
'      ["Freeze",    null,           3, true,  false],',
'    ];',
'    this.MODES = ["CLASSIC", "3X_INFINITE", "SURVIVAL"];',
'    this.modeIdx = 0; this.themeIdx = 0; this.bestWave = 1;',
'    this.deckMode = "MASTER_12"; this.heroIdx = 0;',
'    this.reset();',
'  }',
'  get gameMode() { return this.MODES[this.modeIdx]; }',
'  get theme()    { return THEMES[this.themeIdx]; }',
'',
'  reset() {',
'    this.state = STATE_PLAYING;',
'    this.playerElixir = ELIXIR_START; this.aiElixir = ELIXIR_START;',
'    this.elapsedTime = 0; this.selectedCard = 0;',
'    this.flashMsg = null; this.flashTimer = 0;',
'    this.playerWon = false; this.isDoubleElixir = false; this.screenShake = 0;',
'    this.lightningTimer = 15.0; this.lightningAlpha = 0;',
'    this.waveNumber = 1; this.waveTimer = 15.0; this.runeTimer = 20.0;',
'    const W = SCREEN_W, H = SCREEN_H;',
'    this.playerKing   = new KingTower(W/2, H-60, "player");',
'    this.playerTowerL = new PrincessTower(W/4, H-160, "player");',
'    this.playerTowerR = new PrincessTower(3*W/4, H-160, "player");',
'    this.aiKing       = new KingTower(W/2, 60, "ai");',
'    this.aiTowerL     = new PrincessTower(W/4, 160, "ai");',
'    this.aiTowerR     = new PrincessTower(3*W/4, 160, "ai");',
'    if (this.gameMode === "SURVIVAL") {',
'      this.aiKing.hp = this.aiKing.maxHp = 999999;',
'      this.aiTowerL.hp = this.aiTowerL.maxHp = 999999;',
'      this.aiTowerR.hp = this.aiTowerR.maxHp = 999999;',
'    }',
'    this.playerTowers = [this.playerKing, this.playerTowerL, this.playerTowerR];',
'    this.aiTowers     = [this.aiKing, this.aiTowerL, this.aiTowerR];',
'    this.playerUnits = []; this.aiUnits = [];',
'    this.projectiles = []; this.particles = []; this.floatingTexts = []; this.runes = [];',
'    this.aiCtrl = new AIController();',
'    this.hero = new HeroCommander(HeroCommander.HEROES[this.heroIdx], "player");',
'    this.perkMgr = new PerkManager();',
'    this.deckQueue = Array.from({length: this.CARDS.length}, (_, i) => i).sort(() => Math.random() - 0.5);',
'    this.handIndices = [this.deckQueue.shift(), this.deckQueue.shift(), this.deckQueue.shift(), this.deckQueue.shift()];',
'    this.nextIndex = this.deckQueue.shift();',
'  }',
'  cycleHero() {',
'    this.heroIdx = (this.heroIdx + 1) % HeroCommander.HEROES.length;',
'    this.hero = new HeroCommander(HeroCommander.HEROES[this.heroIdx], "player");',
'    this.showFlash(`Hero Commander: ${this.hero.kind}`);',
'  }',
'  toggleDeckMode() {',
'    this.deckMode = this.deckMode === "MASTER_12" ? "PRO_CYCLE" : "MASTER_12";',
'    this.selectedCard = 0; this.showFlash(`Deck Mode: ${this.deckMode}`);',
'  }',
'  cycleMode() {',
'    this.modeIdx = (this.modeIdx + 1) % this.MODES.length;',
'    this.reset(); this.showFlash(`Mode: ${this.gameMode}`);',
'  }',
'  cycleTheme() {',
'    this.themeIdx = (this.themeIdx + 1) % THEMES.length;',
'    this.showFlash(`Theme: ${this.theme.name}`);',
'  }',
'  showFlash(msg) { this.flashMsg = msg; this.flashTimer = 1.2; }',
'',
'  spawnUnit(kindOrCls, x, y, team, isSwarm = false) {',
'    sfx.playDeploy();',
'    let cls = kindOrCls;',
'    if (typeof kindOrCls === "string") {',
'      const map = { Knight, Archer, Giant, Wizard, Skeleton, Valkyrie, Prince, Cannon: CannonBuilding, InfDragon: InfernoDragon, MegaKnight };',
'      cls = map[kindOrCls];',
'    }',
'    const list = team === "player" ? this.playerUnits : this.aiUnits;',
'    if (team === "player" && cls === CannonBuilding) { const u = new cls(x, y, team); this.perkMgr.applyToUnit(u); this.playerTowers.push(u); }',
'    else if (team === "ai" && cls === CannonBuilding) { this.aiTowers.push(new cls(x, y, team)); }',
'    else if (isSwarm) {',
'      [[-14,-14], [14,-14], [-14,14], [14,14]].forEach(([ox, oy]) => {',
'        const u = new cls(x+ox, y+oy, team); if (team==="player") this.perkMgr.applyToUnit(u);',
'        list.push(u); this.particles.push(new Particle(x+ox, y+oy, 0, 0, team==="player"?C.CYAN:C.AI, 12, 0.3));',
'      });',
'    } else {',
'      const u = new cls(x, y, team); if (team==="player") this.perkMgr.applyToUnit(u);',
'      list.push(u); this.particles.push(new Particle(x, y, 0, 0, team==="player"?C.CYAN:C.AI, 16, 0.35));',
'    }',
'  }',
'  castSpell(name, x, y, team) {',
'    if (name === "Fireball") {',
'      sfx.playDeploy(); const c = CONFIG.Fireball;',
'      this.projectiles.push(new Projectile(x, y - 350, x, y, 650, c.damage, c.radius, team, "meteor"));',
'      this.screenShake = 0.25;',
'    } else if (name === "Freeze") {',
'      sfx.playFreeze(); const c = CONFIG.Freeze;',
'      const targets = team === "player" ? [...this.aiUnits, ...this.aiTowers] : [...this.playerUnits, ...this.playerTowers];',
'      targets.forEach(t => {',
'        if (t.alive && hypot(t.x - x, t.y - y) <= c.radius) {',
'          t.freezeTimer = Math.max(t.freezeTimer, c.duration);',
'          this.floatingTexts.push(new FloatingText(t.x, t.y - 20, "❄️ FREEZE!", C.FREEZE));',
'        }',
'      });',
'      for (let i = 0; i < 35; i++) {',
'        const ang = Math.random() * Math.PI * 2, spd = randFloat(20, 100);',
'        this.particles.push(new Particle(x, y, Math.cos(ang)*spd, Math.sin(ang)*spd, C.FREEZE, randFloat(4, 8), 0.6));',
'      }',
'    }',
'  }',
'  tryDeploy(mx, my) {',
'    if (my >= SCREEN_H - 100) return;',
'    const cardIdx = this.deckMode === "MASTER_12" ? this.selectedCard : this.handIndices[this.selectedCard];',
'    const [name, cls, cost, isSpell, isSwarm] = this.CARDS[cardIdx];',
'    if (this.playerElixir < cost) { this.showFlash("Not enough Elixir!"); return; }',
'    if (isSpell) { this.playerElixir -= cost; this.perkMgr.addSpentElixir(cost); this.castSpell(name, mx, my, "player"); }',
'    else {',
'      if (my <= RIVER_BOTTOM) { this.showFlash("Deploy on your side!"); return; }',
'      for (const t of [...this.playerTowers, ...this.aiTowers]) {',
'        if (t.alive && mx >= t.rect.left-10 && mx <= t.rect.right+10 && my >= t.rect.top-10 && my <= t.rect.bottom+10) {',
'          this.showFlash("Cannot deploy on tower!"); return;',
'        }',
'      }',
'      this.playerElixir -= cost; this.perkMgr.addSpentElixir(cost); this.spawnUnit(cls, mx, my, "player", isSwarm);',
'    }',
'    if (this.deckMode === "PRO_CYCLE") {',
'      const playedIdx = this.handIndices[this.selectedCard];',
'      this.handIndices[this.selectedCard] = this.nextIndex;',
'      this.nextIndex = this.deckQueue.shift();',
'      this.deckQueue.push(playedIdx);',
'    }',
'  }',
'',
'  update(dt) {',
'    if (this.state !== STATE_PLAYING) return;',
'    this.elapsedTime += dt; this.hero.update(dt);',
'    const mult = this.gameMode === "3X_INFINITE" ? 3.0 : (this.isDoubleElixir ? 2.0 : 1.0);',
'    this.playerElixir = clamp(this.playerElixir + ELIXIR_REGEN_RATE * mult * dt, 0, ELIXIR_MAX);',
'    this.aiElixir     = clamp(this.aiElixir     + ELIXIR_REGEN_RATE * mult * dt, 0, ELIXIR_MAX);',
'',
'    if (this.gameMode === "CLASSIC" && !this.isDoubleElixir && this.elapsedTime >= 60) {',
'      this.isDoubleElixir = true; this.screenShake = 0.4; sfx.playDoubleElixir();',
'      this.floatingTexts.push(new FloatingText(SCREEN_W/2, SCREEN_H/2, "⚡ 2X ELIXIR! ⚡", C.GOLD, true, 1.5));',
'    }',
'    if (this.isDoubleElixir || this.gameMode === "3X_INFINITE") {',
'      this.lightningTimer -= dt;',
'      if (this.lightningTimer <= 0) {',
'        this.lightningTimer = randFloat(8.0, 18.0); this.lightningAlpha = 0.7; this.screenShake = 0.15; sfx.playThunder();',
'      }',
'    }',
'    if (this.lightningAlpha > 0) this.lightningAlpha = Math.max(0, this.lightningAlpha - 1.5 * dt);',
'',
'    this.runeTimer -= dt;',
'    if (this.runeTimer <= 0 && this.runes.length < 2) {',
'      this.runeTimer = 25.0; const rx = pick([BRIDGE_LEFT_X, BRIDGE_RIGHT_X, SCREEN_W/2]);',
'      this.runes.push(new Rune(rx, RIVER_MID + randInt(-15, 15), pick(["rage", "heal"])));',
'    }',
'    if (this.gameMode === "SURVIVAL") {',
'      this.waveTimer -= dt;',
'      if (this.waveTimer <= 0) {',
'        this.waveTimer = 15.0; this.waveNumber++; this.bestWave = Math.max(this.bestWave, this.waveNumber);',
'        this.floatingTexts.push(new FloatingText(SCREEN_W/2, RIVER_TOP + 40, `🧟 WAVE ${this.waveNumber}!`, C.RED, true, 1.5));',
'        const cnt = Math.min(6, 1 + Math.floor(this.waveNumber / 2));',
'        for (let i = 0; i < cnt; i++) {',
'          const kind = pick(["Giant", "Prince", "Valkyrie", "Wizard", "Skeleton", "InfDragon", "MegaKnight"]);',
'          const bx = pick([BRIDGE_LEFT_X, BRIDGE_RIGHT_X]);',
'          this.spawnUnit(kind, bx + randInt(-20,20), AI_HALF_BOTTOM - randInt(20, 60), "ai", kind==="Skeleton");',
'        }',
'      }',
'    }',
'    if (this.screenShake > 0) this.screenShake = Math.max(0, this.screenShake - dt);',
'    if (this.flashMsg) { this.flashTimer -= dt; if (this.flashTimer <= 0) this.flashMsg = null; }',
'',
'    if (this.gameMode !== "SURVIVAL") {',
'      this.aiElixir = this.aiCtrl.update(dt, this.aiElixir, (c,x,y,t,s)=>this.spawnUnit(c,x,y,t,s), (sp,x,y,t)=>this.castSpell(sp,x,y,t), this.aiTowers, this.playerUnits, this.aiUnits, this.gameMode, this);',
'      this.aiElixir = clamp(this.aiElixir, 0, ELIXIR_MAX);',
'    }',
'',
'    const allAI = [...this.aiUnits, ...this.aiTowers], allPl = [...this.playerUnits, ...this.playerTowers];',
'    for (const p of this.projectiles) p.update(dt, p.team === "player" ? allAI : allPl, this.particles, this.floatingTexts);',
'    this.projectiles = this.projectiles.filter(p => p.alive);',
'',
'    for (const t of this.playerTowers) t.update(dt, allAI, this.projectiles, this.particles);',
'    for (const t of this.aiTowers)     t.update(dt, allPl, this.projectiles, this.particles);',
'',
'    const liveAIT = this.aiTowers.filter(t=>t.alive), livePlT = this.playerTowers.filter(t=>t.alive);',
'    const liveAllT = [...liveAIT, ...livePlT];',
'    const pu = [...this.playerUnits], au = [...this.aiUnits];',
'    for (const u of pu) u.update(dt, au, liveAIT, pu, liveAllT, this.projectiles, this.floatingTexts, this.particles);',
'    for (const u of au) u.update(dt, pu, livePlT, au, liveAllT, this.projectiles, this.floatingTexts, this.particles);',
'',
'    for (const r of this.runes) r.update(dt, [...pu, ...au], this.particles, this.floatingTexts);',
'    this.runes = this.runes.filter(r => r.alive);',
'',
'    this.particles = this.particles.filter(p => p.update(dt));',
'    this.floatingTexts = this.floatingTexts.filter(ft => ft.update(dt));',
'    ',
'    const oldAICount = this.aiUnits.length + this.aiTowers.length;',
'    this.playerUnits = this.playerUnits.filter(u => u.alive);',
'    this.aiUnits     = this.aiUnits.filter(u => u.alive);',
'    this.playerTowers= this.playerTowers.filter(t => t.alive);',
'    this.aiTowers    = this.aiTowers.filter(t => t.alive);',
'    const newAICount = this.aiUnits.length + this.aiTowers.length;',
'    if (this.perkMgr.perksAcquired.has("OVERFLOW") && oldAICount > newAICount) {',
'      this.playerElixir = Math.min(ELIXIR_MAX, this.playerElixir + 1.0);',
'      this.floatingTexts.push(new FloatingText(SCREEN_W/2, SCREEN_H - 120, "+1 ELIXIR OVERFLOW!", C.PURPLE));',
'    }',
'',
'    if (!this.aiKing.alive && this.gameMode !== "SURVIVAL") { this.playerWon = true; this.state = STATE_GAME_OVER; sfx.playVictory(); }',
'    else if (!this.playerKing.alive) { this.playerWon = false; this.state = STATE_GAME_OVER; sfx.playDefeat(); }',
'  }',
'',
'  draw(ctx) {',
'    const ox = this.screenShake > 0 ? randInt(-4, 4) : 0, oy = this.screenShake > 0 ? randInt(-4, 4) : 0;',
'    const th = this.theme;',
'    const isNight = this.isDoubleElixir || this.gameMode === "3X_INFINITE";',
'    const bgCol = isNight && th.nightBg ? th.nightBg : th.bg;',
'    const rivCol= isNight && th.nightRiver ? th.nightRiver : th.river;',
'    ',
'    ctx.fillStyle = bgCol; ctx.fillRect(0, 0, SCREEN_W, SCREEN_H);',
'    ctx.fillStyle = rivCol; ctx.fillRect(0+ox, RIVER_TOP+oy, SCREEN_W, RIVER_BOTTOM - RIVER_TOP);',
'    for (const bx of [BRIDGE_LEFT_X, BRIDGE_RIGHT_X]) {',
'      ctx.fillStyle = th.bridge; ctx.fillRect(bx - BRIDGE_W/2 + ox, RIVER_TOP + oy, BRIDGE_W, RIVER_BOTTOM - RIVER_TOP);',
'      ctx.strokeStyle = "#000000"; ctx.lineWidth = 2; ctx.strokeRect(bx - BRIDGE_W/2 + ox, RIVER_TOP + oy, BRIDGE_W, RIVER_BOTTOM - RIVER_TOP);',
'    }',
'    for (const r of this.runes) r.draw(ctx, ox, oy);',
'    for (const t of [...this.playerTowers, ...this.aiTowers]) t.draw(ctx, ox, oy);',
'    for (const u of this.aiUnits) u.draw(ctx, ox, oy);',
'    for (const u of this.playerUnits) u.draw(ctx, ox, oy);',
'    for (const p of this.projectiles) p.draw(ctx, ox, oy);',
'    for (const pt of this.particles) pt.draw(ctx, ox, oy);',
'    for (const ft of this.floatingTexts) ft.draw(ctx, ox, oy);',
'',
'    if (this.lightningAlpha > 0) {',
'      ctx.fillStyle = `rgba(255, 255, 255, ${this.lightningAlpha})`;',
'      ctx.fillRect(0, 0, SCREEN_W, SCREEN_H);',
'    }',
'',
'    ctx.fillStyle = "rgba(15, 23, 42, 0.9)"; ctx.fillRect(0, 0, SCREEN_W, 35);',
'    ctx.fillStyle = this.gameMode !== "CLASSIC" ? C.GOLD : C.CYAN; ctx.font = "600 12px Outfit, sans-serif";',
'    ctx.textAlign = "left"; ctx.fillText(`Mode[M]: ${this.gameMode.slice(0,3)}`, 5, 22);',
'    ctx.fillStyle = C.WHITE; ctx.fillText(`Deck[D]: ${this.deckMode.slice(0,3)}`, 110, 22);',
'    ctx.textAlign = "right"; ctx.fillText(`Thm[T]: ${th.name.split(" ")[1].slice(0,3)}`, SCREEN_W - 5, 22);',
'    if (this.gameMode === "SURVIVAL") {',
'      ctx.fillStyle = C.RED; ctx.font = "bold 13px Outfit, sans-serif"; ctx.textAlign = "center";',
'      ctx.fillText(`W:${this.waveNumber}`, 240, 22);',
'    } else {',
'      const mm = String(Math.floor(this.elapsedTime / 60)).padStart(2,"0"), ss = String(Math.floor(this.elapsedTime % 60)).padStart(2,"0");',
'      ctx.fillStyle = this.isDoubleElixir ? C.GOLD : C.WHITE; ctx.font = "bold 18px Roboto Mono, monospace"; ctx.textAlign = "center";',
'      ctx.fillText(`${mm}:${ss}`, 240, 22);',
'    }',
'',
'    const heroCol = this.hero.cdTimer === 0 ? C.GOLD : "#64748b";',
'    ctx.fillStyle = "rgba(15, 23, 42, 0.85)"; rrect(ctx, 5, 42, 145, 26, 6); ctx.fill();',
'    ctx.strokeStyle = heroCol; ctx.lineWidth = 1; rrect(ctx, 5, 42, 145, 26, 6); ctx.stroke();',
'    ctx.fillStyle = heroCol; ctx.font = "bold 11px Outfit, sans-serif"; ctx.textAlign = "left";',
'    ctx.fillText(`👑 Hero[H]: ${this.hero.kind.slice(0,3)} ${this.hero.cdTimer===0 ? "READY" : Math.floor(this.hero.cdTimer)+"s"}`, 10, 59);',
'',
'    if (this.perkMgr.perksAvailable > 0) {',
'      ctx.fillStyle = C.GOLD; rrect(ctx, 155, 42, 145, 26, 6); ctx.fill();',
'      ctx.fillStyle = C.BLACK; ctx.font = "bold 11px Outfit, sans-serif"; ctx.textAlign = "left";',
'      ctx.fillText("🌟 UPGRADE READY [E]!", 160, 59);',
'    } else if (this.perkMgr.perksAcquired.size > 0) {',
'      ctx.fillStyle = "rgba(15, 23, 42, 0.85)"; rrect(ctx, 155, 42, 145, 26, 6); ctx.fill();',
'      ctx.fillStyle = C.PURPLE; ctx.font = "bold 11px Outfit, sans-serif"; ctx.textAlign = "left";',
'      ctx.fillText(`🌟 Perks: ${this.perkMgr.perksAcquired.size} active`, 160, 59);',
'    }',
'',
'    ctx.fillStyle = "rgba(15, 23, 42, 0.92)"; ctx.fillRect(0, SCREEN_H - 100, SCREEN_W, 100);',
'    ctx.strokeStyle = "rgba(255,255,255,0.15)"; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(0, SCREEN_H - 100); ctx.lineTo(SCREEN_W, SCREEN_H - 100); ctx.stroke();',
'    ',
'    ctx.fillStyle = C.ELIX_BG; rrect(ctx, 10, SCREEN_H - 95, SCREEN_W - 20, 16, 6); ctx.fill();',
'    const fillW = Math.floor((SCREEN_W - 20) * (this.playerElixir / ELIXIR_MAX));',
'    if (fillW > 0) { ctx.fillStyle = C.PURPLE; rrect(ctx, 10, SCREEN_H - 95, fillW, 16, 6); ctx.fill(); }',
'    ctx.strokeStyle = C.WHITE; ctx.lineWidth = 1; rrect(ctx, 10, SCREEN_H - 95, SCREEN_W - 20, 16, 6); ctx.stroke();',
'    ctx.fillStyle = C.WHITE; ctx.font = "bold 11px Outfit, monospace"; ctx.textAlign = "left"; ctx.fillText(`Elixir: ${Math.floor(this.playerElixir)}/10`, 18, SCREEN_H - 86);',
'',
'    if (this.deckMode === "MASTER_12") {',
'      const cW = 35, cH = 58, gap = 3, totalW = this.CARDS.length * cW + (this.CARDS.length - 1) * gap;',
'      const sx = (SCREEN_W - totalW) / 2, bY = SCREEN_H - cH - 6;',
'      this.CARDS.forEach(([name, , cost, isSpell], i) => {',
'        const cx = sx + i * (cW + gap), aff = this.playerElixir >= cost, sel = i === this.selectedCard;',
'        ctx.fillStyle = isSpell ? "#7c2d12" : (aff ? "#1e293b" : "#0f172a");',
'        rrect(ctx, cx, bY, cW, cH, 5); ctx.fill();',
'        if (sel) { ctx.strokeStyle = C.GOLD; ctx.lineWidth = 2; rrect(ctx, cx-2, bY-2, cW+4, cH+4, 6); ctx.stroke(); }',
'        else if (!aff) { ctx.fillStyle = "rgba(0,0,0,0.55)"; rrect(ctx, cx, bY, cW, cH, 5); ctx.fill(); }',
'        ctx.fillStyle = isSpell ? C.SPELL : (aff ? C.PLAYER : "#475569");',
'        ctx.beginPath(); ctx.arc(cx + cW/2, bY + 18, 11, 0, Math.PI*2); ctx.fill();',
'        ctx.fillStyle = C.WHITE; ctx.font = "bold 11px Outfit, monospace"; ctx.textAlign = "center"; ctx.fillText(name.slice(0, 2), cx + cW/2, bY + 18);',
'        ctx.font = "600 9px Outfit, sans-serif"; ctx.fillText(name.slice(0, 3), cx + cW/2, bY + 38);',
'        ctx.fillStyle = aff ? C.GOLD : "#64748b"; ctx.font = "bold 11px Outfit, monospace"; ctx.textAlign = "right"; ctx.fillText(String(cost), cx + cW - 4, bY + 12);',
'        const kn = i < 10 ? String((i+1)%10) : (i===10 ? "-" : "=");',
'        ctx.fillStyle = C.CYAN; ctx.font = "9px Roboto Mono, monospace"; ctx.textAlign = "left"; ctx.fillText(kn, cx + 2, bY + 12);',
'      });',
'    } else {',
'      const cW = 64, cH = 62, gap = 8, totalW = 4 * cW + 3 * gap + 80;',
'      const sx = (SCREEN_W - totalW) / 2, bY = SCREEN_H - cH - 6;',
'      for (let i = 0; i < 4; i++) {',
'        const cardIdx = this.handIndices[i];',
'        const [name, , cost, isSpell] = this.CARDS[cardIdx];',
'        const cx = sx + i * (cW + gap), aff = this.playerElixir >= cost, sel = i === this.selectedCard;',
'        ctx.fillStyle = isSpell ? "#7c2d12" : (aff ? "#1e293b" : "#0f172a");',
'        rrect(ctx, cx, bY, cW, cH, 6); ctx.fill();',
'        if (sel) { ctx.strokeStyle = C.GOLD; ctx.lineWidth = 2; rrect(ctx, cx-2, bY-2, cW+4, cH+4, 8); ctx.stroke(); }',
'        else if (!aff) { ctx.fillStyle = "rgba(0,0,0,0.55)"; rrect(ctx, cx, bY, cW, cH, 6); ctx.fill(); }',
'        ctx.fillStyle = isSpell ? C.SPELL : (aff ? C.PLAYER : "#475569");',
'        ctx.beginPath(); ctx.arc(cx + cW/2, bY + 20, 14, 0, Math.PI*2); ctx.fill();',
'        ctx.fillStyle = C.WHITE; ctx.font = "bold 14px Outfit, monospace"; ctx.textAlign = "center"; ctx.fillText(name.slice(0, 2), cx + cW/2, bY + 20);',
'        ctx.font = "600 11px Outfit, sans-serif"; ctx.fillText(name.slice(0, 5), cx + cW/2, bY + 44);',
'        ctx.fillStyle = aff ? C.GOLD : "#64748b"; ctx.font = "bold 13px Outfit, monospace"; ctx.textAlign = "right"; ctx.fillText(String(cost), cx + cW - 6, bY + 14);',
'        ctx.fillStyle = C.CYAN; ctx.font = "11px Roboto Mono, monospace"; ctx.textAlign = "left"; ctx.fillText(String(i+1), cx + 4, bY + 14);',
'      }',
'      const nx = sx + 4 * (cW + gap) + 10;',
'      ctx.fillStyle = "#0f172a"; rrect(ctx, nx, bY, 56, 62, 6); ctx.fill();',
'      ctx.strokeStyle = "#475569"; ctx.lineWidth = 1; rrect(ctx, nx, bY, 56, 62, 6); ctx.stroke();',
'      ctx.fillStyle = C.CYAN; ctx.font = "10px Outfit, sans-serif"; ctx.textAlign = "center"; ctx.fillText("NEXT", nx + 28, bY + 12);',
'      const [nName, , nCost, nSpell] = this.CARDS[this.nextIndex];',
'      ctx.fillStyle = nSpell ? C.SPELL : C.PLAYER; ctx.beginPath(); ctx.arc(nx + 28, bY + 30, 12, 0, Math.PI*2); ctx.fill();',
'      ctx.fillStyle = C.WHITE; ctx.font = "bold 11px Outfit, monospace"; ctx.fillText(nName.slice(0, 2), nx + 28, bY + 30);',
'      ctx.fillStyle = C.GOLD; ctx.font = "bold 11px Outfit, monospace"; ctx.fillText(String(nCost), nx + 28, bY + 52);',
'    }',
'',
'    if (this.flashMsg) { ctx.fillStyle = C.RED; ctx.font = "bold 18px Outfit, monospace"; ctx.textAlign = "center"; ctx.fillText(this.flashMsg, SCREEN_W/2, RIVER_BOTTOM + 20); }',
'    if (this.state === STATE_GAME_OVER) {',
'      ctx.fillStyle = "rgba(0,0,0,0.82)"; ctx.fillRect(0, 0, SCREEN_W, SCREEN_H);',
'      ctx.textAlign = "center"; ctx.textBaseline = "middle";',
'      const col = this.playerWon ? C.GOLD : C.RED, msg = this.playerWon ? "VICTORY!" : "DEFEAT";',
'      ctx.fillStyle = col; ctx.font = "bold 52px Cinzel, monospace"; ctx.fillText(msg, SCREEN_W/2, SCREEN_H/2 - 140);',
'      ',
'      ctx.fillStyle = "#0f172a"; rrect(ctx, 35, SCREEN_H/2 - 80, SCREEN_W - 70, 160, 10); ctx.fill();',
'      ctx.strokeStyle = C.GOLD; ctx.lineWidth = 2; rrect(ctx, 35, SCREEN_H/2 - 80, SCREEN_W - 70, 160, 10); ctx.stroke();',
'      ctx.fillStyle = C.GOLD; ctx.font = "bold 20px Outfit, sans-serif"; ctx.fillText("📊 BATTLE MVP & ANALYTICS", SCREEN_W/2, SCREEN_H/2 - 55);',
'      ',
'      const allFought = [...this.playerUnits, ...this.playerTowers, ...this.aiUnits, ...this.aiTowers];',
'      let mvp = null, bd = -1;',
'      for (const e of allFought) { if (e.damageDealt > bd) { bd = e.damageDealt; mvp = e; } }',
'      const mvpName = mvp ? `${mvp.kindName} (${mvp.team.toUpperCase()})` : "None";',
'      const mvpDmg = mvp ? mvp.damageDealt : 0;',
'      ',
'      ctx.fillStyle = C.WHITE; ctx.font = "600 15px Outfit, sans-serif"; ctx.fillText(`🏆 MATCH MVP: ${mvpName}`, SCREEN_W/2, SCREEN_H/2 - 15);',
'      ctx.fillStyle = C.CYAN;  ctx.fillText(`💥 Total Damage Dealt: ${mvpDmg}`, SCREEN_W/2, SCREEN_H/2 + 15);',
'      ctx.fillStyle = C.PURPLE;ctx.fillText(`🌟 Perks Acquired: ${this.perkMgr.perksAcquired.size}`, SCREEN_W/2, SCREEN_H/2 + 45);',
'      ',
'      ctx.fillStyle = C.WHITE; ctx.font = "600 18px Outfit, sans-serif"; ctx.fillText("Press R to Play Again", SCREEN_W/2, SCREEN_H/2 + 120);',
'    }',
'  }',
'}',
'',
'// ============================================================',
'// 11. MAIN LOOP & EVENT LISTENERS',
'// ============================================================',
'const canvas = document.getElementById("gameCanvas");',
'const ctx    = canvas.getContext("2d");',
'const game   = new GameState();',
'',
'canvas.addEventListener("click", e => {',
'  const r = canvas.getBoundingClientRect();',
'  game.tryDeploy((e.clientX - r.left) * (canvas.width / r.width), (e.clientY - r.top) * (canvas.height / r.height));',
'});',
'document.addEventListener("keydown", e => {',
'  sfx.init();',
'  if (game.state === STATE_GAME_OVER && (e.key === "r" || e.key === "R")) { game.reset(); return; }',
'  if (e.key === "r" || e.key === "R") game.reset();',
'  else if (e.key === "m" || e.key === "M") game.cycleMode();',
'  else if (e.key === "t" || e.key === "T") game.cycleTheme();',
'  else if (e.key === "d" || e.key === "D") game.toggleDeckMode();',
'  else if (e.key === "c" || e.key === "C") game.cycleHero();',
'  else if (e.key === "h" || e.key === "H") game.hero.activateUltimate(game);',
'  else if (e.key === "e" || e.key === "E") game.perkMgr.claimPerk(game);',
'  else {',
'    const num = parseInt(e.key);',
'    const maxC = game.deckMode === "MASTER_12" ? 12 : 4;',
'    if (!isNaN(num) && num >= 1 && num <= 9) {',
'      const idx = num - 1;',
'      if (idx < maxC) { game.selectedCard = idx; sfx.playSelect(); }',
'    } else if (e.key === "0" && game.deckMode === "MASTER_12") { game.selectedCard = 9; sfx.playSelect(); }',
'    else if (e.key === "-" && game.deckMode === "MASTER_12") { game.selectedCard = 10; sfx.playSelect(); }',
'    else if (e.key === "=" && game.deckMode === "MASTER_12") { game.selectedCard = 11; sfx.playSelect(); }',
'  }',
'});',
'canvas.addEventListener("wheel", e => {',
'  e.preventDefault(); if (game.state === STATE_GAME_OVER) return;',
'  const maxC = game.deckMode === "MASTER_12" ? 12 : 4;',
'  game.selectedCard = (game.selectedCard + (e.deltaY > 0 ? 1 : -1) + maxC) % maxC; sfx.playSelect();',
'}, { passive: false });',
'canvas.addEventListener("mousemove", e => {',
'  const r = canvas.getBoundingClientRect(), my = (e.clientY - r.top) * (canvas.height / r.height);',
'  const cardIdx = game.deckMode === "MASTER_12" ? game.selectedCard : game.handIndices[game.selectedCard];',
'  const isSpell = game.CARDS[cardIdx][3];',
'  canvas.style.cursor = my > SCREEN_H - 100 ? "pointer" : (my > RIVER_BOTTOM || isSpell) ? "crosshair" : "not-allowed";',
'});',
'',
'let lastTime = null;',
'function loop(ts) {',
'  if (lastTime === null) lastTime = ts;',
'  const dt = Math.min((ts - lastTime) / 1000, FPS_MAX_DT);',
'  lastTime = ts; game.update(dt); game.draw(ctx); requestAnimationFrame(loop);',
'}',
'requestAnimationFrame(loop);',
)

# ── HTML tail ────────────────────────────────────────────────────────────────
w('</script>', '</body>', '</html>')

output = '\n'.join(PARTS)
with open('index.html', 'w', encoding='utf-8', newline='\n') as f:
    f.write(output)

lines = output.count('\n') + 1
st.write(f'index.html written: {lines} lines, {len(output)} bytes')
assert 'pygame' not in output, 'Found pygame reference!'
assert 'import ' not in output or 'importScripts' in output, 'Found Python import!'
st.write('Sanity checks passed.')


# ====== 自動生成的測試執行區塊 ======
if __name__ == "__main__":
    st.write("---")
    st.subheader("函數測試區塊")
    if st.button("執行 w"):
        try:
            res = w() # 請視需要自行補上參數
            st.write("執行結果:", res)
        except Exception as e:
            st.error(f"執行出錯，可能需要提供參數：{e}")
